### ISSUE TITLE
WebUI not launching

### ISSUE THREAD

**Issue by Ziyango** [NUROISEA/anime-webui-colab#35] opened 2023-11-05 16:20 UTC
account_circle
👍 Utility script imported.
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
🚨🚨                 IF YOU DONT HAVE COLAB PRO                         🚨🚨
🚨🚨        THIS NOTEBOOK WILL STOP FUNCTIONING IMMEDIATELY             🚨🚨
🚨🚨                       OR AT 10 MINUTES                             🚨🚨
🚨🚨                         OR RANDOMLY                                🚨🚨
🚨🚨                                                                    🚨🚨
🚨🚨                                                                    🚨🚨
🚨🚨       you can ignore this if you have pro btw, but yeah            🚨🚨
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
🌟 Installing stable-diffusion-webui...
📦 Installing 12 extensions...
  └ aspect-ratio-preset
  └ batchlinks
  └ cutoff
  └ dynamic-thresholding
  └ images-browser
  └ latent-couple-two-shot
  └ session-organizer
  └ state
  └ tagcomplete
  └ tiled-multidiffusion-upscaler
  └ tokenizer
  └ tunnels
🔧 Fetching configs...
💉 Fetching embeddings...
🩹 Applying web UI Colab patches...
🩹 Applying Colab memory patches...
env: LD_PRELOAD=/content/libtcmalloc_minimal.so.4
📦 Installing aria2...
⏬ Downloading Anything-V3-full-pruned.safetensors to /content/stable-diffusion-webui/models/Stable-diffusion...
⏬ Downloading anything.vae.pt to /content/stable-diffusion-webui/models/VAE...
/content/stable-diffusion-webui
fatal: No names found, cannot describe anything.
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: ## 1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning K-diffusion into /content/stable-diffusion-webui/repositories/k-diffusion...
Cloning CodeFormer into /content/stable-diffusion-webui/repositories/CodeFormer...
Cloning BLIP into /content/stable-diffusion-webui/repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements
Installing pycloudflared

Installing ImageReward requirement for image browser

Launching Web UI with arguments: --opt-sdp-attention --lowram --no-hashing --enable-insecure-extension-access --no-half-vae --disable-safe-unpickle --gradio-queue --ckpt /content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3-full-pruned.safetensors --vae-path /content/stable-diffusion-webui/models/VAE/anything.vae.pt --share
2023-11-05 16:18:36.509923: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-05 16:18:36.509983: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-05 16:18:36.510023: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /content/stable-diffusion-webui/launch.py:38 in <module>                                         │
│                                                                                                  │
│   35                                                                                             │
│   36                                                                                             │
│   37 if __name__ == "__main__":                                                                  │
│ ❱ 38 │   main()                                                                                  │
│   39                                                                                             │
│                                                                                                  │
│ /content/stable-diffusion-webui/launch.py:34 in main                                             │
│                                                                                                  │
│   31 │   if args.test_server:                                                                    │
│   32 │   │   configure_for_tests()                                                               │
│   33 │                                                                                           │
│ ❱ 34 │   start()                                                                                 │
│   35                                                                                             │
│   36                                                                                             │
│   37 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /content/stable-diffusion-webui/modules/launch_utils.py:340 in start                             │
│                                                                                                  │
│   337                                                                                            │
│   338 def start():                                                                               │
│   339 │   print(f"Launching {'API server' if '--nowebui' in sys.argv else 'Web UI'} with argum   │
│ ❱ 340 │   import webui                                                                           │
│   341 │   os.system(f"""sed -i -e "s/dict()))$/dict())).cuda()/gm" /content/stable-diffusion-w   │
│   342 │   if '--nowebui' in sys.argv:                                                            │
│   343 │   │   webui.api_only()                                                                   │
│                                                                                                  │
│ /content/stable-diffusion-webui/webui.py:35 in <module>                                          │
│                                                                                                  │
│    32                                                                                            │
│    33 startup_timer.record("import torch")                                                       │
│    34                                                                                            │
│ ❱  35 import gradio                                                                              │
│    36 startup_timer.record("import gradio")                                                      │
│    37                                                                                            │
│    38 import ldm.modules.encoders.modules  # noqa: F401                                          │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/gradio/__init__.py:3 in <module>                         │
│                                                                                                  │
│    1 import pkgutil                                                                              │
│    2                                                                                             │
│ ❱  3 import gradio.components as components                                                      │
│    4 import gradio.inputs as inputs                                                              │
│    5 import gradio.outputs as outputs                                                            │
│    6 import gradio.processing_utils                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/gradio/components.py:55 in <module>                      │
│                                                                                                  │
│     52 from PIL import Image as _Image  # using _ to minimize namespace pollution                │
│     53 from typing_extensions import Literal                                                     │
│     54                                                                                           │
│ ❱   55 from gradio import processing_utils, utils                                                │
│     56 from gradio.blocks import Block, BlockContext                                             │
│     57 from gradio.events import (                                                               │
│     58 │   Blurrable,                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/gradio/utils.py:339 in <module>                          │
│                                                                                                  │
│   336 │   return await iterator.__anext__()                                                      │
│   337                                                                                            │
│   338                                                                                            │
│ ❱ 339 class AsyncRequest:                                                                        │
│   340 │   """                                                                                    │
│   341 │   The AsyncRequest class is a low-level API that allow you to create asynchronous HTTP   │
│   342 │   Compared to making calls by using httpx directly, AsyncRequest offers several advant   │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/gradio/utils.py:358 in AsyncRequest                      │
│                                                                                                  │
│   355 │   You can see example usages in test_utils.py.                                           │
│   356 │   """                                                                                    │
│   357 │                                                                                          │
│ ❱ 358 │   client = httpx.AsyncClient()                                                           │
│   359 │                                                                                          │
│   360 │   class Method(str, Enum):                                                               │
│   361 │   │   """                                                                                │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/httpx/_client.py:1397 in __init__                        │
│                                                                                                  │
│   1394 │   │   allow_env_proxies = trust_env and app is None and transport is None               │
│   1395 │   │   proxy_map = self._get_proxy_map(proxies, allow_env_proxies)                       │
│   1396 │   │                                                                                     │
│ ❱ 1397 │   │   self._transport = self._init_transport(                                           │
│   1398 │   │   │   verify=verify,                                                                │
│   1399 │   │   │   cert=cert,                                                                    │
│   1400 │   │   │   http1=http1,                                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/httpx/_client.py:1445 in _init_transport                 │
│                                                                                                  │
│   1442 │   │   if app is not None:                                                               │
│   1443 │   │   │   return ASGITransport(app=app)                                                 │
│   1444 │   │                                                                                     │
│ ❱ 1445 │   │   return AsyncHTTPTransport(                                                        │
│   1446 │   │   │   verify=verify,                                                                │
│   1447 │   │   │   cert=cert,                                                                    │
│   1448 │   │   │   http1=http1,                                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py:275 in __init__             │
│                                                                                                  │
│   272 │   │   ssl_context = create_ssl_context(verify=verify, cert=cert, trust_env=trust_env)    │
│   273 │   │                                                                                      │
│   274 │   │   if proxy is None:                                                                  │
│ ❱ 275 │   │   │   self._pool = httpcore.AsyncConnectionPool(                                     │
│   276 │   │   │   │   ssl_context=ssl_context,                                                   │
│   277 │   │   │   │   max_connections=limits.max_connections,                                    │
│   278 │   │   │   │   max_keepalive_connections=limits.max_keepalive_connections,                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

**Comment by Drakenhof** [comment] 2023-11-06 15:40
Same problem here, with any notebook of the ones I tried :(

**Comment by orcuswankenobi** [comment] 2023-11-06 18:55
yeah same

**Comment by Drakenhof** [comment] 2023-11-06 20:02
Is not a problem of google colab with webiu; I have been able to launch other notebooks from another sources

**Comment by Drakenhof** [comment] 2023-11-08 08:59
I have been researching a bit, and looks like the bug is caused by the new version of Google Colab. To solve the issue, write the following instalation command on the notebook, just before the phyton.launch command (should be at the end of the code text):

!pip. install httpx==0.24.1

**Comment by orcuswankenobi** [comment] 2023-11-08 15:21
> I have been researching a bit, and looks like the bug is caused by the new version of Google Colab. To solve the issue, write the following instalation command on the notebook, just before the phyton.launch command (should be at the end of the code text). Remember to do it before running the notebook:
> 
> !pip. install httpx==0.24.1

didnt work

**Comment by Ayaya70** [comment] 2023-11-08 17:35
Yo, I've the same problem and tested what Drakenhof said but still didn't work, unfortunately. I use Provide Your Own Models WebUI Colab 

> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /content/stable-diffusion-webui/launch.py:38 in <module>                                         │
│                                                                                                  │
│   35                                                                                             │
│   36                                                                                             │
│   37 if __name__ == "__main__":                                                                  │
│ ❱ 38 │   main()                                                                                  │
│   39                                                                                             │
│                                                                                                  │
│ /content/stable-diffusion-webui/launch.py:34 in main                                             │
│                                                                                                  │
│   31 │   if args.test_server:                                                                    │
│   32 │   │   configure_for_tests()                                                               │
│   33 │                                                                                           │
│ ❱ 34 │   start()                                                                                 │
│   35                                                                                             │
│   36                                                                                             │
│   37 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /content/stable-diffusion-webui/modules/launch_utils.py:340 in start                             │
│                                                                                                  │
│   337                                                                                            │
│   338 def start():                                                                               │
│   339 │   print(f"Launching {'API server' if '--nowebui' in sys.argv else 'Web UI'} with argum   │
│ ❱ 340 │   import webui                                                                           │
│   341 │   os.system(f"""sed -i -e "s/dict()))$/dict())).cuda()/gm" /content/stable-diffusion-w   │
│   342 │   if '--nowebui' in sys.argv:                                                            │
│   343 │   │   webui.api_only()                                                                   │
│                                                                                                  │
│ /content/stable-diffusion-webui/webui.py:35 in <module>                                          │
│                                                                                                  │
│    32                                                                                            │
│    33 startup_timer.record("import torch")                                                       │
│    34                                                                                            │
│ ❱  35 import gradio                                                                              │
│    36 startup_timer.record("import gradio")                                                      │
│    37                                                                                            │
│    38 import ldm.modules.encoders.modules  # noqa: F401                                          │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/gradio/__init__.py:3 in <module>                         │
│                                                                                                  │
│    1 import pkgutil                                                                              │
│    2                                                                                             │
│ ❱  3 import gradio.components as components                                                      │
│    4 import gradio.inputs as inputs                                                              │
│    5 import gradio.outputs as outputs                                                            │
│    6 import gradio.processing_utils                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/gradio/components.py:55 in <module>                      │
│                                                                                                  │
│     52 from PIL import Image as _Image  # using _ to minimize namespace pollution                │
│     53 from typing_extensions import Literal                                                     │
│     54                                                                                           │
│ ❱   55 from gradio import processing_utils, utils                                                │
│     56 from gradio.blocks import Block, BlockContext                                             │
│     57 from gradio.events import (                                                               │
│     58 │   Blurrable,                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/gradio/utils.py:339 in <module>                          │
│                                                                                                  │
│   336 │   return await iterator.__anext__()                                                      │
│   337                                                                                            │
│   338                                                                                            │
│ ❱ 339 class AsyncRequest:                                                                        │
│   340 │   """                                                                                    │
│   341 │   The AsyncRequest class is a low-level API that allow you to create asynchronous HTTP   │
│   342 │   Compared to making calls by using httpx directly, AsyncRequest offers several advant   │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/gradio/utils.py:358 in AsyncRequest                      │
│                                                                                                  │
│   355 │   You can see example usages in test_utils.py.                                           │
│   356 │   """                                                                                    │
│   357 │                                                                                          │
│ ❱ 358 │   client = httpx.AsyncClient()                                                           │
│   359 │                                                                                          │
│   360 │   class Method(str, Enum):                                                               │
│   361 │   │   """                                                                                │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/httpx/_client.py:1397 in __init__                        │
│                                                                                                  │
│   1394 │   │   allow_env_proxies = trust_env and app is None and transport is None               │
│   1395 │   │   proxy_map = self._get_proxy_map(proxies, allow_env_proxies)                       │
│   1396 │   │                                                                                     │
│ ❱ 1397 │   │   self._transport = self._init_transport(                                           │
│   1398 │   │   │   verify=verify,                                                                │
│   1399 │   │   │   cert=cert,                                                                    │
│   1400 │   │   │   http1=http1,                                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/httpx/_client.py:1445 in _init_transport                 │
│                                                                                                  │
│   1442 │   │   if app is not None:                                                               │
│   1443 │   │   │   return ASGITransport(app=app)                                                 │
│   1444 │   │                                                                                     │
│ ❱ 1445 │   │   return AsyncHTTPTransport(                                                        │
│   1446 │   │   │   verify=verify,                                                                │
│   1447 │   │   │   cert=cert,                                                                    │
│   1448 │   │   │   http1=http1,                                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py:275 in __init__             │
│                                                                                                  │
│   272 │   │   ssl_context = create_ssl_context(verify=verify, cert=cert, trust_env=trust_env)    │
│   273 │   │                                                                                      │
│   274 │   │   if proxy is None:                                                                  │
│ ❱ 275 │   │   │   self._pool = httpcore.AsyncConnectionPool(                                     │
│   276 │   │   │   │   ssl_context=ssl_context,                                                   │
│   277 │   │   │   │   max_connections=limits.max_connections,                                    │
│   278 │   │   │   │   max_keepalive_connections=limits.max_keepalive_connections,                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

**Comment by Drakenhof** [comment] 2023-11-08 18:04
Im uploading a screenshot of how I have my copy of the anything v4 notebook; the command is the one within the box. Noticie this are the final pharagraphs of the code, so you will have to scroll down all the notebook to find them
![anything v4](https://github.com/NUROISEA/anime-webui-colab/assets/16356595/58db3e17-6732-4f91-975e-a64f52f11928)

**Comment by NUROISEA** [comment] 2023-11-09 01:18
I pushed an attempt for a fix for this, please let me know if it works or breaks again

Also reopening this, didn't intend to close this issue

**Comment by Drakenhof** [comment] 2023-11-09 18:43
> I pushed an attempt for a fix for this, please let me know if it works or breaks again
> 
> Also reopening this, didn't intend to close this issue

Tried a random notebook and it worked :)

**Closed** 2024-03-18 05:17 UTC
